### ISSUE TITLE
temp link to cal.techatnyu.org

### ISSUE THREAD

**Issue by grungerabbit** [TechAtNYU/tech-nyu-site#72]
make the CTAs and copy link to cal.techatnyu.org for now

**Comment by ethanresnick** [comment]
This is fine by me but, out of curiosity, why did we develop the cal in a separate repo in the first place (rather than a branch here)? Was it because I was still working on the Livescript conversion? If so, my bad. But, now that that's done, we should be thinking about _how_ this integration is actually going to work before you and yelly put more time into this, because the integration could be kinda tricky and require changing some code.

**Comment by AbhiAgarwal** [comment]
@ethanresnick I think they wanted it to be a part of the universal-header they are working on as well. So the same code would be used on the main site and the universal-headers (?).
